### ISSUE TITLE
Thirst mod compatibility

### ISSUE THREAD

**Issue by ghost** [Flenix/HUDWidgets#4]
Hi Flenix, 
Could you create an other hud mod (mc 1.7.10) just to add compatibility of this mod I already tried out but I don't know how to do.
The mods : 
https://github.com/thetorine/thirstmod
Thanks

**Comment by ghost** [comment]
Hi ?

**Comment by Fureniku** [comment]
No, as Thirst is for 1.8 and HUDWidgets won't be going to 1.8. I'm skipping straight to 1.9 when it gets released, as are many modders.

**Comment by ghost** [comment]
I'm just asking for an compatibility for the thirst mod 1.7.10 ? I already tried to do it, but it does'nt work. So could you do it ?

**Comment by Fureniku** [comment]
I could but it requires compatability from both ends, and I assume their 1.7.10 build is discontinued. I'd also need a copy of their 1.7.10 source to build against, and without altering their mod, you'd just have two thirst bars.

If you can convince them to add support (Just detect if my mod is installed and if so, disable GUI elements) then I'll do it :)

**Comment by ghost** [comment]
Ok, I will ask him, it's just two of my prefferate mods :+1:

**Comment by ghost** [comment]
I asked yhim, you can start the compatibility release (If he can't disable the thirst I will do it.)

**Comment by ghost** [comment]
Also I forget to say when I playing with these two mods, there's no normal thirst hud. It rendering being deleting by HUD widget. So I think you know what'S it mean.

**Comment by ghost** [comment]
So ?

**Comment by Fureniku** [comment]
So I will do it when I have the time. 
I make and release my mods for free in my spare time, and other mods currently take high priority over this. I've got a big slot of free time in the end of October so I'll probably do it then, but in the mean time I don't appreciate being nagged every 12 hours.

**Comment by ghost** [comment]
Ok, scuse me, thank you, and take your time
